server:
  port: 3000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
