spring:
  application:
    name: urlOrchestrator
  datasource:
    hikari:
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  profiles:
    active:
      - dev

# snowflake properties
snowflake:
  epoch: 1772792966   # 2026-03-06
  worker-id-bits: 10
  sequence-bits: 12
  worker-id: 1